package ru.integration.flumecontainer.config.source;

import org.apache.log4j.Logger;
import ru.integration.flumecontainer.unit.Unit;
import ru.integration.flumecontainer.unit.UnitImpl;

import java.io.*;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Created by mfilippov on 2017-04-18.
 */
public class InitSourceFileList implements InitSource {

    private Logger logger= Logger.getLogger(InitSourceFileList.class);

    String directory;

    String propPattern;

    String fileExtension;

    private List<String> files = new ArrayList<String>();

    HashMap<String,Unit> source = new HashMap();

    private Properties initializer = null;
/*
    {
        files= new ArrayList<String>();
        files.add("src/main/resources/my-agent.properties");
    }
*/

    public Unit getUnit(String unitName){
        Unit unit = source.get(unitName);
        return unit;
    }

    public Map<String,Unit> getUnits(){
        return this.source;
    }

    public void addUnit(String unitName, Properties properties){
        try {
            Unit unit=new UnitImpl(unitName,properties);
            FileOutputStream os=new FileOutputStream(unitName+fileExtension);
            properties.store(os,"Autogenerated by flumecontainer");
            os.flush();
            os.close();
            source.put(unitName,unit);
        } catch (IOException e) {
            logger.info(String.format("Could not save file with name ", unitName+fileExtension),e);
        }
    }

    public void addUnit(String unitName, Properties properties, List<String> tags) {
        try {
            Unit unit=new UnitImpl(unitName,properties);
            unit.setTags(tags);
            FileOutputStream os=new FileOutputStream(unitName+fileExtension);
            properties.store(os,"Autogenerated by flumecontainer");
            os.flush();
            os.close();
            source.put(unitName,unit);
        } catch (IOException e) {
            logger.info(String.format("Could not save file with name ", unitName+fileExtension),e);
        }
    }

    public void deleteUnit(String unitName){
        Unit unit=source.get(unitName);
        if(unit.getStatus()== UnitImpl.Status.STARTED){
            unit.stop();
        }
        source.remove(unitName);
    }

    public Object getSourceInitializer() {
        return initializer;
    }

    public void setSourceInitializer(Properties initializer) {
        this.initializer=initializer;
    }

    public void init() {
        try {
            this.directory = initializer.getProperty("flume.source.dir", "");
            if (this.directory.equals("")){
                throw new CouldNotFindPropertyException("Directory is not set");
            }
            this.propPattern = initializer.getProperty("flume.source.conf-pattern", "");
            if(this.propPattern.equals("")){
                logger.warn("File pattern is not set! <.*> template selected.");
            }
            this.fileExtension = initializer.getProperty("flume.source.fileExtension", "");
            if(this.fileExtension.equals("")){
                logger.info("File extension is not set!");
            }
            Pattern pattern = Pattern.compile(this.propPattern);
            File dir = new File(this.directory);
            if (dir.isDirectory()) {
                logger.info("Search in dir:"+dir.getName());
                for (File file : dir.listFiles()) {
                    String name = file.getName();
                    Matcher matcher = pattern.matcher(name);
                    if (matcher.matches()) {
                        logger.info("found "+file.getName());
                        this.files.add(file.getAbsolutePath());
                    }
                }
            }else{
                logger.info("Not a directory: "+this.directory);
            }
            if (files != null&&files.size()>0) {
                for (String file : files) {
                    try {
                        logger.info("Initialize file " + file);
                        Properties props = new Properties();
                        props.load(new FileInputStream(file));
                        String filname = new File(file).getName().split("\\.")[0];
                        source.put(filname, new UnitImpl(filname,props));
                    } catch (IOException e) {
                        logger.error("error " + e.toString());
                    }
                }
            } else {
                logger.warn("Source is empty!");
            }
        } catch (Exception ex) {
            logger.error("Initialization failed ", ex);
        }
    }
}
